spring:
  profiles: 
    active: test
mybatis:
  config-location: classpath:/mybatis-config.xml
logging: 
  level: 
    root: INFO
// security: 
//   user: 
//     name: admin 
//     password: 123456
pagehelper: 
  helper-dialect: mysql 
  reasonable: true 
  support-methods-arguments: true